final commit on my hobby
Clementify/LESSON1_AND_2_TASK5_OBI-CLEMENTINA pull request #1
Opened 2023-05-05 11:01 UTC by Clementify

I am done with my Lesson 1 and 2 task5, kindly review @ChidiPatrick and @Promise-J.

2023-05-05 14:51 UTC, ChidiPatrick requested changes
Do the correction and let me know

2023-05-05 14:51 UTC, ChidiPatrick commented on html/myhobby.html
> +            <img src="/image/Tailoring.jpg" alt="tailoring">
close your img tag

2023-05-05 18:43 UTC, Clementify commented on html/myhobby.html
> +            <img src="/image/Tailoring.jpg" alt="tailoring">
Alright sir,

2023-05-05 18:58 UTC, Clementify commented
I have closed it sir. Kindly review @ChidiPatrick

2023-05-08 11:04 UTC, ChidiPatrick approved these changes
Great work!
You nailed it!

2023-05-08 11:08 UTC, Clementify commented
THank you sir.

On Mon, May 8, 2023 at 12:04 PM Chidiebele ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> Great work!
> You nailed it!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Clementify/LESSON1_AND_2_TASK5_OBI-CLEMENTINA/pull/1#pullrequestreview-1416591670>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A7CHUNRPLUNV637FTWXFLUDXFDHLXANCNFSM6AAAAAAXW6YUSA>
> .
> You are receiving this because you authored the thread.Message ID:
> <Clementify/LESSON1_AND_2_TASK5_OBI-CLEMENTINA/pull/1/review/1416591670@
> github.com>
>

2023-05-08 11:09 UTC, merged